### ISSUE TITLE
Install fails - CDT not available

### ISSUE THREAD

**Issue by pdoubleya** [prismofeverything/schmetterling#1]
Hi

I cloned schmetterling and tried 'lein run' - got

```
Could not find artifact prismofeverything:cdt:jar:1.2.6.3 in central (http://repo1.maven.org/maven2/)
Could not find artifact prismofeverything:cdt:jar:1.2.6.3 in clojars (https://clojars.org/repo/)
```

It seems maybe you are working with a private fork of CDT? The repo I found for CDT under your account is not under the namespace "prismofeverything" and is at version 1.2.6.2 - trying to push that version to the local repo didn't help as there are references to schmetterling:cdt somewhere in the code (I can paste more info if that helps).

Looking forward to trying this out, thanks!
Patrick

**Comment by prismofeverything** [comment]
Ah, you are correct!  I had to make some modifications to cdt to support exclusion filters in exception events.  I have pushed both my fork of cdt and the latest Schmetterling features (including display of locals and the source fns).  This is still very much a work in progress but I welcome any feedback!
